### ISSUE TITLE
error PUID ?

### ISSUE THREAD

**Issue by Geczy** [rabilrbl/TGBOT#26]
i dont even what chatgpt i just want bing, how do i avoid this

```
$ docker logs tgbot-bot-1
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/tgbot/main.py", line 9, in <module>
    from tgbot.libs.chatgpt import ChatGPT
  File "/app/tgbot/libs/chatgpt.py", line 13, in <module>
    gptBot = GPTChatbot(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 816, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 165, in __init__
    self.__check_credentials()
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 189, in __check_credentials
    self.login()
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 333, in login
    auth = Authenticator(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/OpenAIAuth.py", line 38, in __init__
    raise ValueError("PUID is required")
ValueError: PUID is required
```

**Comment by rabilrbl** [comment]
Check and validate your `BING_COOKIES`

**Comment by rabilrbl** [comment]
Closing on inactivity. Reopen if needed
